# Generated by Django 5.1.6 on 2025-03-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tareas',
            options={'ordering': ['-creado']},
        ),
    ]
